In [1]:

from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split

In [2]:
X,y = load_diabetes(return_X_y=True)

In [3]:
print(X.shape)
print(y.shape)

(442, 10)
(442,)


In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=2)

In [5]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [6]:
print(reg.coef_)
print(reg.intercept_)

[  -9.15865318 -205.45432163  516.69374454  340.61999905 -895.5520019
  561.22067904  153.89310954  126.73139688  861.12700152   52.42112238]
151.88331005254167


In [7]:

y_pred = reg.predict(X_test)
r2_score(y_test,y_pred)

0.4399338661568969

In [8]:
import random

class MBGDRegressor:
    
    def __init__(self,batch_size,learning_rate=0.01,epochs=100):
        
        self.coef_ = None
        self.intercept_ = None
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size = batch_size
        
    def fit(self,X_train,y_train):
        # init your coefs
        self.intercept_ = 0
        self.coef_ = np.ones(X_train.shape[1])
        
        for i in range(self.epochs):
            
            for j in range(int(X_train.shape[0]/self.batch_size)):
                
                idx = random.sample(range(X_train.shape[0]),self.batch_size)
                
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_
                #print("Shape of y_hat",y_hat.shape)
                intercept_der = -2 * np.mean(y_train[idx] - y_hat)
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)

                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ = self.coef_ - (self.lr * coef_der)
        
        print(self.intercept_,self.coef_)
    
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [9]:
mbr = MBGDRegressor(batch_size=int(X_train.shape[0]/50),learning_rate=0.01,epochs=100)

In [10]:
mbr.fit(X_train,y_train)

151.57518167526507 [  30.80004054 -144.19108784  456.34646502  310.95833485  -27.56478869
  -94.76679238 -200.2653645   106.96360448  411.91315865  112.39651833]


In [11]:

y_pred = mbr.predict(X_test)

In [12]:
y_pred

array([152.00196505, 195.67241459, 130.85742207, 104.41741925,
       260.34210102, 249.45487966, 110.60097601, 114.82906337,
        94.1601264 , 186.81249399, 148.19401426, 173.48304593,
       180.97941667, 139.02534801, 282.18717202,  86.03797708,
       196.92806697, 146.45316002, 133.77924142, 132.26149675,
       144.0916478 , 174.87931199, 154.70814246, 175.0093521 ,
       126.41005029, 221.29080744, 199.64082175, 104.81218144,
        55.1839119 , 238.03576513, 241.11740249, 113.82796608,
        68.10317652,  98.68431341, 202.97522196, 163.78268673,
       162.70909796, 192.92713756, 112.89337663, 237.92254142,
       139.58340007, 122.08555197, 185.88112116, 186.38856267,
       174.38072409, 143.29899355, 171.07694419, 294.21466495,
       108.64726508, 173.9780421 , 250.45272631, 139.05636641,
       149.36845839, 130.69600131, 191.36471057,  99.69666211,
       136.02736137,  77.23954588, 158.2127616 , 152.08992095,
       163.56147807, 163.69297654, 103.39049569, 221.70

In [13]:

r2_score(y_test,y_pred)

0.45330717286379596

In [14]:
from sklearn.linear_model import SGDRegressor

In [15]:

sgd = SGDRegressor(learning_rate='constant',eta0=0.1)

In [16]:
batch_size = 35

for i in range(100):
    
    idx = random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train[idx],y_train[idx])


In [17]:

sgd.coef_

array([  57.81361705,  -89.42899606,  338.99863097,  253.27191956,
         17.16628953,  -22.1393889 , -170.06158592,  128.31240181,
        303.25785316,  112.21843222])

In [18]:
sgd.intercept_

array([147.92704475])

In [19]:
y_pred = sgd.predict(X_test)

In [20]:

r2_score(y_test,y_pred)

0.430918595812811